name: build-test-publish

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # ---------------- RESTORE ----------------
    - name: Restore dependencies
      run: |
        dotnet restore Practica2o/HolaMnddoApp/HolaMnddoApp.csproj
        dotnet restore Practica2o/HolaMnddoApp.Tests/HolaMnddoApp.Tests.csproj

    # ---------------- TEST ----------------
    - name: Run unit tests
      run: dotnet test Practica2o/HolaMnddoApp.Tests/HolaMnddoApp.Tests.csproj --no-build --verbosity normal

    # ---------------- DOCKER LOGIN ----------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ---------------- DOCKER BUILD ----------------
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-csharp:latest Practica2o/HolaMnddoApp

    # ---------------- DOCKER PUSH ----------------
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hola-mundo-csharp:latest

    # ---------------- RENDER DEPLOY ----------------
    - name: Notify deployment service
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

