name: build-test-publish

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # RESTORE
    - name: Restore dependencies
      run: dotnet restore HolaMnddoApp/HolaMnddoApp.csproj

    # BUILD
    - name: Build project
      run: dotnet build HolaMnddoApp/HolaMnddoApp.csproj --no-restore

    # TESTS
    - name: Run unit tests
      run: dotnet test HolaMnddoApp.Tests/HolaMnddoApp.Tests.csproj --no-build --verbosity normal

    # LOGIN DOCKER
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # BUILD DOCKER IMAGE
    - name: Build Docker image
      run: docker build -t reynaldogj/hola-mundo-csharp:latest HolaMnddoApp/

    # PUSH TO DOCKER HUB
    - name: Push Docker image
      run: docker push reynaldogj/hola-mundo-csharp:latest

    # NOTIFY RENDER OR OTHER SERVICE
    - name: Notify deployment service
      run: echo "Deployment completed!"


